### ISSUE TITLE
AttributeError: 'FaxService' object has no attribute 'IPRestrictOnOff'

### ISSUE THREAD

**Issue by syntaxkim** [linkhub-sdk/popbill.py#2]
After updating the package from 1.11.0 to 1.12.0, the AttributeError occurs at this point below

 File "/usr/local/lib/python3.7/site-packages/popbill/faxService.py", line 232, in sendFax
   RequestNum)
 File "/usr/local/lib/python3.7/site-packages/popbill/faxService.py", line 304, in sendFax_multi
   result = self._httppost_files('/FAX', postData, files, CorpNum, UserID)
 File "/usr/local/lib/python3.7/site-packages/popbill/base.py", line 376, in _httppost_files
   headers["Authorization"] = "Bearer " + self._getToken(CorpNum).session_token
 File "/usr/local/lib/python3.7/site-packages/popbill/base.py", line 289, in _getToken
   ServiceID_TEST if self.IsTest else ServiceID_REAL, CorpNum, self.__scopes, None if self.IPRestrictOnOff else "*")
AttributeError: 'FaxService' object has no attribute 'IPRestrictOnOff'

Environment
python 3.7.2

**Comment by syntaxkim** [comment]
fixed
